package com.java.coding.interviews.practise.hackerrank;

/**
 * Look-and-Say Sequence
 * Difficulty Level : Medium
 * Last Updated : 21 Jun, 2021
 * Find the n’th term in Look-and-say (Or Count and Say) Sequence. The look-and-say sequence is the sequence of below integers:
 * 1, 11, 21, 1211, 111221, 312211, 13112221, 1113213211, …
 *
 * How is above sequence generated?
 * n’th term in generated by reading (n-1)’th term.
 *
 * The first term is "1"
 *
 * Second term is "11", generated by reading first term as "One 1"
 * (There is one 1 in previous term)
 *
 * Third term is "21", generated by reading second term as "Two 1"
 *
 * Fourth term is "1211", generated by reading third term as "One 2 One 1"
 *
 * and so on
 * How to find n’th term?
 *
 * Example:
 *
 * Input: n = 3
 * Output: 21
 *
 * Input: n = 5
 * Output: 111221
 */
public class CountAndSayProblem {

    public static void main(String[] args) {
        System.out.println(findPattern(3));
        System.out.println(findPattern(5));
    }

    public static String findPattern(int N){
        if(N==1) return "1";
        if(N==2) return "11";

        String S = "11";
        for(int i=3;i<=N;i++) {
            S += "$";
            int L = S.length();
            char[] C = S.toCharArray();
            int count=1;
            String temp="";
            for(int j=1;j<L;j++){
                if(C[j]!=C[j-1]){
                    temp+=count+0;
                    temp+=C[j-1];
                    count=1;
                }else
                    count++;
            }
            S=temp;
        }
        return S;
    }

}
